Repository FRONT-END-BOOTCAMP-PLUS-4/sik-share, pull requests merged in 2025-05, with the labels that each got.

#7 Biome 추가 설정 및 의존성 수정
  app/page.tsx
  biome.json
  package-lock.json
  package.json
Labels: chore

#35 공통 컴포넌트 - Calendar 오류 수정
  app/globals.css
  components/common/InputCalendar.tsx
  components/ui/calendar.tsx
  package-lock.json
  package.json
Labels: chore, style

#39 공통 컴포넌트 - 스타일 수정 및 tabs, subHeader 추가
  app/page.tsx
  components/common/ListCard.tsx
  components/common/SubHeader.tsx
  components/ui/badge.tsx
  components/ui/button.tsx
  components/ui/tabs.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: feat, chore, style

#38 PC 레이아웃 구성
  .github/PULL_REQUEST_TEMPLATE.md
  app/globals.css
  app/layout.tsx
  app/page.tsx
  app/test/page.tsx
  components/common/Footer.tsx
  components/lotties/IntroLottie.tsx
  components/lotties/RobotLottie.tsx
  public/assets/lotties/Intro.lottie
  public/assets/lotties/Robot.lottie
Labels: feat, chore, style

#46 메인 페이지 초기 UI 구성
  app/components/CommunicateSection.tsx
  app/components/HeroSection.tsx
  app/components/MapSection.tsx
  app/globals.css
  app/layout.tsx
  app/page.tsx
  app/test/page.tsx
  components/common/Footer.tsx
  components/lotties/CommunicateLottie.tsx
  components/lotties/IntroLottie.tsx
  components/lotties/MapLottie.tsx
  components/ui/button.tsx
  package-lock.json
  package.json
  public/assets/lotties/Communicate.lottie
  public/assets/lotties/Ingredient.lottie
  public/assets/lotties/Map.lottie
Labels: feat, asset, style

#48 3D 나눔함 페이지에 바텀시트 초안 구현
  app/globals.css
  app/layout.tsx
  app/share-box/components/BottomSheet.tsx
  app/share-box/test/page.tsx
  components/common/shares/Carousel.tsx
  components/common/shares/Content.tsx
  components/ui/drawer.tsx
  components/ui/sheet.tsx
  package-lock.json
  package.json
Labels: feat, style

#51 feat: 알림 페이지 초안 구현
  app/notification/components/Tab.tsx
  app/notification/components/TabList.tsx
  app/notification/page.tsx
  components/common/Header.tsx
  tailwind.config.ts
Labels: feat, style

#52 메인 페이지 스크롤 및 활동 통계 UI 구성
  app/components/CommunicateSection.tsx
  app/components/EndSection.tsx
  app/components/ScrollSection.tsx
  app/hooks/useCountUp.ts
  app/layout.tsx
  app/page.tsx
  components/lotties/CartLottie.tsx
  components/lotties/FoodLottie.tsx
  public/assets/lotties/Cart.lottie
  public/assets/lotties/Food.lottie
Labels: feat, chore, asset, style

#55 회원가입 로직 작성
  app/api/auth/[...nextauth]/route.ts
  app/api/users/exist/route.ts
  app/api/users/signup/route.ts
  app/auth/components/ButtonSection.tsx
  app/auth/components/LastLoginInfo.tsx
  app/auth/components/LoginButton.tsx
  app/auth/components/Title.tsx
  app/auth/page.tsx
  app/layout.tsx
  app/onboarding/page.tsx
  app/post-login/page.tsx
  application/usecases/auth/CheckUserExistenceUsecase.ts
  application/usecases/auth/CreateUserUsecase.ts
  application/usecases/auth/dto/CheckUserExistenceResultDto.ts
  application/usecases/auth/dto/CreateUserDto.ts
  components/common/SessionProvider.tsx
  domain/entities/Neighborhood.ts
  domain/entities/User.ts
  domain/repositories/NeighborhoodRepository.ts
  domain/repositories/UserRepository.ts
  infra/repositories/prisma/PrismaNeighborhoodRepository.ts
  infra/repositories/prisma/PrismaUserRepository.ts
  package-lock.json
  package.json
  prisma/schema.prisma
  public/assets/images/social/google.svg
  public/assets/images/social/kakao.svg
  public/assets/images/social/naver.svg
  types/next-auth.d.ts
  types/types.ts
  types/user.ts
Labels: feat

#63 채팅 페이지 초안 구현
  app/chat/[roomId]/shares/page.tsx
  app/chat/[roomId]/together/page.tsx
  app/chat/components/ChatHeader.tsx
  app/chat/components/ChatInput.tsx
  app/chat/components/ChatList.tsx
  app/chat/components/ChatMessage.tsx
  app/chat/components/ChatMessageList.tsx
  app/chat/components/ChatRoom.tsx
  app/chat/components/ShareInfo.tsx
  app/chat/components/Tab.tsx
  app/chat/components/TogetherInfo.tsx
  app/chat/page.tsx
Labels: feat, style

#62 회원가입, 로그인 구현
  app/api/auth/[...nextauth]/route.ts
  app/api/users/signup/route.ts
  app/auth/onboarding/components/ButtonSection.tsx
  app/auth/onboarding/components/KakaoMap.tsx
  app/auth/onboarding/page.tsx
  app/auth/post-login/page.tsx
  app/hooks/useKakaoReady.ts
  app/layout.tsx
  app/login/components/ButtonSection.tsx
  app/login/components/LastLoginInfo.tsx
  app/login/components/LoginButton.tsx
  app/login/components/Title.tsx
  app/login/page.tsx
  app/onboarding/page.tsx
  application/usecases/auth/CheckUserExistenceUsecase.ts
  application/usecases/auth/CreateUserUsecase.ts
  application/usecases/auth/dto/CheckUserExistenceResultDto.ts
  components/common/Loading.tsx
  components/common/SubHeader.tsx
  components/lotties/LoadingLottie.tsx
  package-lock.json
  package.json
  public/assets/images/map_pin.svg
  public/assets/lotties/loading.lottie
  store/authStore.ts
  store/useAuthStore.ts
  tsconfig.json
  types/next-auth.d.ts
Labels: feat

#64 페이지, API 권한 검사 추가 & 주소 저장 시 행정동 사용
  app/auth/onboarding/components/KakaoMap.tsx
  components/common/Footer.tsx
  middleware.ts
Labels: feat

#65 마이 페이지 - 회원정보 가져오기, 프로필 수정 1차
  app/api/route.ts
  app/api/users/route.ts
  app/api/users/update/route.ts
  app/globals.css
  app/users/[publicId]/page.tsx
  app/users/components/Profile.tsx
  app/users/components/ShareScore.tsx
  app/users/components/UserLocation.tsx
  application/usecases/auth/CreateUserUsecase.ts
  application/usecases/user/GetUserProfileUsecase.ts
  application/usecases/user/UpdateUserProfileUsecase.ts
  application/usecases/user/dto/GetUserProfileDto.ts
  application/usecases/user/dto/UpdateUserProfileDto.ts
  components/common/FormImageUpload.tsx
  components/ui/button.tsx
  components/ui/dialog.tsx
  components/ui/input.tsx
  domain/entities/ProfileImage.ts
  domain/repositories/ImageStorageRepository.ts
  infra/repositories/supabase/SupabaseImageRepository.ts
  lib/supabase.ts
  next.config.ts
  package-lock.json
  package.json
  prisma/schema.prisma
Labels: feat, refactor, style

#66 DowndropButton 및 로그아웃 기능 추가
  app/api/auth/[...nextauth]/route.ts
  app/login/components/LoginButton.tsx
  app/test/page.tsx
  app/users/components/EditProfileButton.tsx
  app/users/components/Profile.tsx
  components/common/AddButton.tsx
  components/common/DropdownButton.tsx
  components/ui/button.tsx
Labels: feat, refactor

#69 로그인 로직 변경
  app/api/auth/[...nextauth]/route.ts
  app/auth/onboarding/page.tsx
  app/auth/post-login/page.tsx
  app/users/[publicId]/page.tsx
  app/users/components/Profile.tsx
  application/usecases/auth/CheckUserExistenceUsecase.ts
  application/usecases/auth/CreateUserUsecase.ts
  application/usecases/auth/dto/CheckUserExistenceResultDto.ts
  components/common/Footer.tsx
  store/authStore.ts
  types/next-auth.d.ts
Labels: fix, refactor

#71 회원 정보 수정 기능 추가 및 카카오 맵 수정
  app/api/users/update/address/route.ts
  app/api/users/update/route.ts
  app/auth/onboarding/page.tsx
  app/layout.tsx
  app/users/[publicId]/edit-address/page.tsx
  app/users/[publicId]/page.tsx
  app/users/components/EditProfileButton.tsx
  app/users/components/Profile.tsx
  app/users/components/UserLocation.tsx
  application/usecases/user/UpdateUserAddressUsecase.ts
  application/usecases/user/UpdateUserProfileUsecase.ts
  application/usecases/user/dto/UpdateUserAddressDto.ts
  components/common/FormImageUpload.tsx
  components/common/KakaoMap.tsx
  components/ui/sonner.tsx
  infra/repositories/supabase/SupabaseImageRepository.ts
  next.config.ts
  package-lock.json
  package.json
Labels: feat, refactor, chore

#75 나눔 등록 기능 구현
  app/api/auth/[...nextauth]/route.ts
  app/api/shareItems/route.ts
  app/api/shares/route.ts
  app/api/users/signup/route.ts
  app/share/new/components/ButtonSection.tsx
  app/share/new/components/FormDetail.tsx
  app/share/new/components/FormMultiImageUpload.tsx
  app/share/new/components/FormSelect.tsx
  app/share/new/components/LocationSelectModal.tsx
  app/share/new/components/Thumbnail.tsx
  app/share/new/hooks/useShareItems.ts
  app/share/new/page.tsx
  application/usecases/share/CreateShareUsecase.ts
  application/usecases/share/GetShareItemsUsecase.ts
  application/usecases/share/dto/CreateShareDto.ts
  components/common/FormImageUpload.tsx
  components/common/FormInput.tsx
  components/common/KakaoMap.tsx
  components/common/SubHeader.tsx
  components/ui/form.tsx
  domain/entities/Neighborhood.ts
  domain/entities/ShareImage.ts
  domain/entities/User.ts
  domain/repositories/ImageStorageRepository.ts
  domain/repositories/share/ShareImageRepository.ts
  domain/repositories/share/ShareItemRepository.ts
  domain/repositories/share/ShareRepository.ts
  infra/repositories/prisma/share/PrismaShareImageRepository.ts
  infra/repositories/prisma/share/PrismaShareItemRepository.ts
  infra/repositories/prisma/share/PrismaShareRepository.ts
  infra/repositories/supabase/SupabaseImageRepository.ts
  lib/constants.ts
  prisma/schema.prisma
  public/assets/images/lucide/camera.svg
  types/types.ts
Labels: feat

#77 채팅 서버 연동 및 1차 구현 완료
  app/api/chat/[chatId]/shares/route.ts
  app/api/chat/[chatId]/together/route.ts
  app/api/chat/list/route.ts
  app/chat/[chatId]/shares/page.tsx
  app/chat/[chatId]/together/page.tsx
  app/chat/[roomId]/shares/page.tsx
  app/chat/[roomId]/together/page.tsx
  app/chat/components/ChatHeader.tsx
  app/chat/components/ChatInput.tsx
  app/chat/components/ChatList.tsx
  app/chat/components/ChatMessage.tsx
  app/chat/components/ChatMessageList.tsx
  app/chat/components/ChatRoom.tsx
  app/chat/components/ShareInfo.tsx
  app/chat/components/Tab.tsx
  app/chat/components/TogetherInfo.tsx
  app/chat/layout.tsx
  app/chat/page.tsx
  app/hooks/useSocket.ts
  app/share-box/page.tsx
  application/usecases/Chat/GetChatListUsecase.ts
  application/usecases/Chat/GetGroupBuyChatInfoUsecase.ts
  application/usecases/Chat/GetGroupBuyChatListUsecase.ts
  application/usecases/Chat/GetGroupBuyChatMessagesUsecase.ts
  application/usecases/Chat/GetShareChatListUsecase.ts
  application/usecases/Chat/dto/ChatDetailDto.ts
  application/usecases/Chat/dto/ChatListItemDto.ts
  application/usecases/Chat/dto/ChatMessageListDto.ts
  application/usecases/Chat/dto/GroupBuyChatListDto.ts
  application/usecases/Chat/dto/GroupBuyChatMessageListDto.ts
  domain/repositories/Chat/ChatListRepository.ts
  domain/repositories/Chat/ChatMessageListRepository.ts
  domain/repositories/Chat/GroupBuyChatMessageRepository.ts
  infra/repositories/prisma/PrismaChatListRepository.ts
  infra/repositories/prisma/PrismaChatMessageListRepository.ts
  infra/repositories/prisma/PrismaGroupBuyChatMessageRepository.ts
  lib/socket.ts
  package-lock.json
  package.json
  prisma/schema.prisma
  store/useChatStore.ts
Labels: feat, chore, style

#76 같이 장보기 등록 기능 구현
  app/api/group-buys/route.ts
  app/api/shares/route.ts
  app/register/components/ButtonSection.tsx
  app/register/components/FormCalendar.tsx
  app/register/components/FormDetail.tsx
  app/register/components/FormMultiImageUpload.tsx
  app/register/components/FormSelect.tsx
  app/register/components/LocationSelectModal.tsx
  app/register/components/Thumbnail.tsx
  app/register/group-buy/page.tsx
  app/register/share/hooks/useShareItems.ts
  app/register/share/page.tsx
  application/usecases/group-buy/CreateGroupBuyUsecase.ts
  application/usecases/group-buy/dto/CreateGroupBuyDto.ts
  application/usecases/share/CreateShareUsecase.ts
  components/common/FormInput.tsx
  components/common/InputCalendar.tsx
  components/ui/calendar.tsx
  components/ui/input.tsx
  domain/entities/ShareImage.ts
  domain/repositories/ImageStorageRepository.ts
  domain/repositories/group-buy/GroupBuyImageRepository.ts
  domain/repositories/group-buy/GroupBuyRepository.ts
  infra/repositories/prisma/group-buy/PrismaGroupBuyImageRepository.ts
  infra/repositories/prisma/group-buy/PrismaGroupBuyRepository.ts
  infra/repositories/supabase/SupabaseImageRepository.ts
  prisma/schema.prisma
Labels: feat

#84 나눔 더미 데이터 생성 스크립트, 워크 플로우 작성
  .github/workflows/daily-dummy-seed.yml
  package-lock.json
  package.json
  seeds/seed-backup.ts
  seeds/seed-daily.ts
  tsconfig.seed.json
Labels: chore

#87 같이 장보기 상세페이지 UI 구성
  app/group-buy/[groupbuyId]/meet/page.tsx
  app/group-buy/[groupbuyId]/page.tsx
  app/map/components/MapList.tsx
  app/share/[shareId]/meet/page.tsx
  app/share/[shareId]/page.tsx
  components/details/AuthorInfo.tsx
  components/details/AvatarGroup.tsx
  components/details/DetailFooter.tsx
  components/details/GroupBadges.tsx
  components/details/KakaoMapDetail.tsx
  global.d.ts
Labels: feat, style

#88 마이페이지 - 후기 / ShortReview api 연동
  app/api/users/history-count/route.ts
  app/api/users/reviews/route.ts
  app/api/users/route.ts
  app/map/components/MapList.tsx
  app/users/[publicId]/page.tsx
  app/users/[publicId]/reviews/page.tsx
  app/users/components/HistoryItemList.tsx
  app/users/components/HistorySection.tsx
  app/users/components/ReviewListItem.tsx
  app/users/components/UsersNav.tsx
  app/users/hooks/useTotalCounts.ts
  app/users/hooks/useUserInfo.ts
  application/usecases/user/GetUserHistoryCountUsecase.ts
  application/usecases/user/GetUserReviewsUsecase.ts
  application/usecases/user/GetUserShortReviewsUsecase.ts
  application/usecases/user/dto/GetUserHistoryCountDto.ts
  application/usecases/user/dto/GetUserReviewsDto.ts
  application/usecases/user/dto/GetUserReviewsResultDto.ts
  application/usecases/user/dto/GetUserShortReviewsDto.ts
  components/common/Loading.tsx
  components/lotties/LoadingFoodLottie.tsx
  components/ui/badge.tsx
  domain/repositories/review/ReviewRepository.ts
  domain/repositories/review/ReviewShortReviewRepository.ts
  domain/repositories/review/ShortReviewOptionRepository.ts
  infra/repositories/prisma/review/PrismaReviewRepository.ts
  infra/repositories/prisma/review/PrismaReviewShortReviewRepository.ts
  infra/repositories/prisma/review/PrismaShortReviewOptionRepository.ts
  seeds/seed-backup.ts
  seeds/seed-daily.ts
Labels: feat, refactor, chore

#90 후기 작성 기능 구현
  app/api/reviews/route.ts
  app/api/reviews/validate/route.ts
  app/api/share-items/route.ts
  app/api/short-review-options/route.ts
  app/register/components/ButtonSection.tsx
  app/register/group-buy/page.tsx
  app/register/share/hooks/useShareItems.ts
  app/register/share/page.tsx
  app/review/new/components/FormRatingSelector.tsx
  app/review/new/hooks/useShortReviewOptions.ts
  app/review/new/hooks/useValidateReviewWritable.ts
  app/review/new/page.tsx
  application/usecases/review/CreateReviewUsecase.ts
  application/usecases/review/GetShortReviewOptionUsecase.ts
  application/usecases/review/ValidateReviewWritableUsecase.ts
  application/usecases/review/dto/CreateReviewDto.ts
  application/usecases/review/dto/ReviewWritableFailDto.ts
  application/usecases/review/dto/ReviewWritableSuccessDto.ts
  components/common/KakaoMap.tsx
  components/common/register/FormButton.tsx
  components/common/register/FormCalendar.tsx
  components/common/register/FormCheckbox.tsx
  components/common/register/FormDetail.tsx
  components/common/register/FormMultiImageUpload.tsx
  components/common/register/FormSelect.tsx
  components/common/register/LocationSelectModal.tsx
  components/common/register/Thumbnail.tsx
  components/ui/checkbox.tsx
  components/ui/input.tsx
  components/ui/select.tsx
  domain/repositories/UserRepository.ts
  domain/repositories/review/ReviewRepository.ts
  domain/repositories/review/ReviewShortReviewRepository.ts
  domain/repositories/review/ShortReviewOptionRepository.ts
  domain/repositories/share/ShareRepository.ts
  hooks/useKakaoReady.ts
  infra/repositories/prisma/PrismaUserRepository.ts
  infra/repositories/prisma/review/PrismaReviewRepository.ts
  infra/repositories/prisma/review/PrismaReviewShortReviewRepository.ts
  infra/repositories/prisma/review/PrismaShortReviewOptionRepository.ts
  infra/repositories/prisma/share/PrismaShareRepository.ts
  package-lock.json
  package.json
  prisma/schema.prisma
  public/assets/images/review-ratings/bad.svg
  public/assets/images/review-ratings/bad_selected.svg
  public/assets/images/review-ratings/good.svg
  public/assets/images/review-ratings/good_selected.svg
  public/assets/images/review-ratings/great.svg
  public/assets/images/review-ratings/great_selected.svg
Labels: feat

#94 같이 장보기 상세조회 api 연동 및 공유하기
  app/api/group-buys/[groupBuyId]/route.ts
  app/api/map/group-buy/route.ts
  app/api/shares/[sharesId]/route.ts
  app/group-buy/[groupbuyId]/meet/page.tsx
  app/group-buy/[groupbuyId]/page.tsx
  app/layout.tsx
  application/usecases/group-buy/GetGroupBuyDetailUsecase.ts
  application/usecases/group-buy/dto/GetGroupBuyDetailDto.ts
  components/common/shares/Carousel.tsx
  components/details/AuthorInfo.tsx
  components/details/AvatarGroup.tsx
  components/details/DetailFooter.tsx
  components/details/GroupBadges.tsx
  components/details/ShareButton.tsx
  components/ui/button.tsx
  domain/repositories/GroupBuyRepository.ts
  domain/repositories/group-buy/GroupBuyRepository.ts
  global.d.ts
  infra/repositories/prisma/PrismGroupBuyRepository.ts
  infra/repositories/prisma/group-buy/PrismaGroupBuyRepository.ts
  package-lock.json
  package.json
  stores/useSessionStore.ts
Labels: feat, chore

#96 채팅 기능 구현 완료
  app/api/chat/[chatId]/shares/complete/route.ts
  app/api/chat/[chatId]/shares/confirm/route.ts
  app/api/chat/[chatId]/together/complete/route.ts
  app/chat/[chatId]/together/page.tsx
  app/chat/components/ChatHeader.tsx
  app/chat/components/ChatInput.tsx
  app/chat/components/ChatList.tsx
  app/chat/components/ChatMessage.tsx
  app/chat/components/ChatMessageList.tsx
  app/chat/components/ChatRoom.tsx
  app/chat/components/ReserveDatePicker.tsx
  app/chat/components/ShareInfo.tsx
  app/chat/components/Tab.tsx
  app/chat/components/TogetherInfo.tsx
  app/chat/page.tsx
  app/chat/test/page.tsx
  application/usecases/Chat/UpdateMeetingDateUseCase.ts
  application/usecases/Chat/UpdateShareStatusUseCase.ts
  application/usecases/Chat/UpdateTogetherStatusUseCase.ts
  application/usecases/Chat/dto/ChatDetailDto.ts
  application/usecases/Chat/dto/ChatMessageListDto.ts
  application/usecases/Chat/dto/UpdateMeetingDateDto.ts
  application/usecases/Chat/dto/UpdateShareStatusDto.ts
  application/usecases/Chat/dto/UpdateTogetherStatusDto.ts
  components/ui/badge.tsx
  components/ui/button.tsx
  domain/repositories/Chat/ChatMessageListRepository.ts
  domain/repositories/Chat/GroupBuyChatMessageRepository.ts
  domain/repositories/Chat/UpdateMeetingDateRepository.ts
  domain/repositories/Chat/UpdateShareStatusRepository.ts
  domain/repositories/Chat/UpdateTogetherStatusRepository.ts
  infra/repositories/prisma/PrismaChatListRepository.ts
  infra/repositories/prisma/PrismaChatMessageListRepository.ts
  infra/repositories/prisma/PrismaGroupBuyChatMessageRepository.ts
  infra/repositories/prisma/PrismaUpdateMeetingDateRepository.ts
  infra/repositories/prisma/PrismaUpdateShareStatusRepository.ts
  infra/repositories/prisma/PrismaUpdateTogetherStatusRepository.ts
  prisma/schema.prisma
Labels: feat, chore, style

#100 마이페이지 - 리스트 수정/삭제 기능 추가
  app/api/group-buys/[groupBuyId]/route.ts
  app/api/shares/[shareId]/route.ts
  app/users/components/EditProfileButton.tsx
  app/users/components/GroupBuyListCard.tsx
  app/users/components/HistoryItemList.tsx
  app/users/components/HistorySection.tsx
  app/users/components/ShareListCard.tsx
  app/users/utils.ts
  application/usecases/group-buy/DeleteGroupBuyUsecase.ts
  application/usecases/share/DeleteShareUsecase.ts
  application/usecases/user/GetUserGroupBuysUsecase.ts
  application/usecases/user/GetUserHistoryCountUsecase.ts
  application/usecases/user/GetUserParticipationsUsecase.ts
  application/usecases/user/GetUserSharesUsecase.ts
  components/common/DeleteDialog.tsx
  components/common/DropdownButton.tsx
  components/ui/alert-dialog.tsx
  components/ui/button.tsx
  domain/repositories/group-buy/GroupBuyRepository.ts
  domain/repositories/share/ShareRepository.ts
  infra/repositories/prisma/group-buy/PrismaGroupBuyRepository.ts
  infra/repositories/prisma/share/PrismaShareRepository.ts
  package-lock.json
  package.json
  prisma/schema.prisma
Labels: feat, chore

#104 dynamic-api 관련 promise 추가, 코드 공통화
  app/api/chat/[chatId]/shares/complete/route.ts
  app/api/chat/[chatId]/shares/confirm/route.ts
  app/api/chat/[chatId]/shares/route.ts
  app/api/chat/[chatId]/together/complete/route.ts
  app/api/chat/[chatId]/together/route.ts
  app/api/group-buys/[groupBuyId]/route.ts
  app/api/shares/[shareId]/route.ts
Labels: fix

#103 chat 폴더명 대소문자 에러 수정
  application/usecases/chat/GetChatListUsecase.ts
  application/usecases/chat/GetGroupBuyChatInfoUsecase.ts
  application/usecases/chat/GetGroupBuyChatListUsecase.ts
  application/usecases/chat/GetGroupBuyChatMessagesUsecase.ts
  application/usecases/chat/GetShareChatListUsecase.ts
  application/usecases/chat/UpdateMeetingDateUseCase.ts
  application/usecases/chat/UpdateShareStatusUseCase.ts
  application/usecases/chat/UpdateTogetherStatusUseCase.ts
  application/usecases/chat/dto/ChatDetailDto.ts
  application/usecases/chat/dto/ChatListItemDto.ts
  application/usecases/chat/dto/ChatMessageListDto.ts
  application/usecases/chat/dto/GroupBuyChatListDto.ts
  application/usecases/chat/dto/GroupBuyChatMessageListDto.ts
  application/usecases/chat/dto/UpdateMeetingDateDto.ts
  application/usecases/chat/dto/UpdateShareStatusDto.ts
  application/usecases/chat/dto/UpdateTogetherStatusDto.ts
  domain/repositories/chat/ChatListRepository.ts
  domain/repositories/chat/ChatMessageListRepository.ts
  domain/repositories/chat/GroupBuyChatMessageRepository.ts
  domain/repositories/chat/UpdateMeetingDateRepository.ts
  domain/repositories/chat/UpdateShareStatusRepository.ts
  domain/repositories/chat/UpdateTogetherStatusRepository.ts
Labels: fix, chore

#109 fix: route 받는 값 에러 수정
  app/api/chat/[chatId]/shares/complete/route.ts
  app/api/chat/[chatId]/shares/confirm/route.ts
  app/api/chat/[chatId]/shares/route.ts
  app/api/chat/[chatId]/together/complete/route.ts
  app/api/chat/[chatId]/together/route.ts
  app/api/group-buys/[groupBuyId]/route.ts
  app/api/shares/[shareId]/route.ts
Labels: fix

#108 feat : 나눔 수정 페이지 api 연동
  app/api/shares/[shareId]/edit/route.ts
  app/api/shares/[shareId]/route.ts
  app/forbidden/page.tsx
  app/share/[shareId]/edit/hooks/useShareFormDetail.ts
  app/share/[shareId]/edit/page.tsx
  application/usecases/share/GetShareFormDetailUsecase.ts
  application/usecases/share/dto/GetShareFormDetailDto.ts
  components/common/register/FormMultiImageUpload.tsx
  errors/HttpError.ts
Labels: feat

#112 feat : 같이 장보기 수정 페이지 구현
  app/api/group-buys/[groupBuyId]/edit/route.ts
  app/api/group-buys/[groupBuyId]/route.ts
  app/group-buy/[groupbuyId]/edit/hooks/useGroupBuyFormDetail.ts
  app/group-buy/[groupbuyId]/edit/page.tsx
  application/usecases/group-buy/GetGroupBuyFormDetailUsecase.ts
  application/usecases/group-buy/UpdateGroupBuyUsecase.ts
  application/usecases/group-buy/dto/GetGroupBuyFormDetailDto.ts
  application/usecases/group-buy/dto/UpdateGroupBuyDto.ts
  domain/repositories/group-buy/GroupBuyImageRepository.ts
  domain/repositories/group-buy/GroupBuyRepository.ts
  infra/repositories/prisma/group-buy/PrismaGroupBuyImageRepository.ts
  infra/repositories/prisma/group-buy/PrismaGroupBuyRepository.ts
Labels: feat

#115 같이 장보기 등록 시 채팅방 생성 로직 추가
  app/api/group-buys/route.ts
  application/usecases/group-buy/CreateGroupBuyUsecase.ts
  domain/repositories/chat/GroupBuyChatParticipantRepository.ts
  domain/repositories/chat/GroupBuyChatRepository.ts
  infra/repositories/prisma/chat/PrismaGroupBuyChatParticipantRepository.ts
  infra/repositories/prisma/chat/PrismaGroupBuyChatRepository.ts
Labels: feat

#120 인증 관련 예외 처리
  app/auth/onboarding/page.tsx
  app/auth/post-login/page.tsx
  lib/authOptions.ts
  middleware.ts
Labels: feat, fix, refactor
