Repository FRONT-END-BOOTCAMP-PLUS-4/sik-share, pull requests merged in 2025-06, with the labels that each got.

#131 마이페이지 나누미 캐릭터 추가
  app/globals.css
  app/users/[publicId]/page.tsx
  app/users/components/MyCharacter.tsx
  app/users/components/MyPoint.tsx
  app/users/components/ShareBoxButton.tsx
  app/users/components/ShareScore.tsx
  app/users/components/model/Ground.tsx
  app/users/components/model/Nanumi.tsx
  app/users/utils.ts
Labels: feat, style

#126 최근 등록한 나눔 항목 등록 제한
  app/api/share-items/route.ts
  app/group-buy/[groupBuyId]/edit/page.tsx
  app/register/group-buy/page.tsx
  app/register/share/page.tsx
  app/review/new/hooks/useValidateReviewWritable.ts
  app/review/new/page.tsx
  app/share/[shareId]/edit/page.tsx
  application/usecases/group-buy/CreateGroupBuyUsecase.ts
  application/usecases/share/GetShareItemsUsecase.ts
  components/common/KakaoMap.tsx
  components/common/register/FormButton.tsx
  domain/repositories/share/ShareItemRepository.ts
  domain/repositories/share/ShareRepository.ts
  infra/repositories/prisma/chat/PrismaGroupBuyChatParticipantRepository.ts
  infra/repositories/prisma/chat/PrismaGroupBuyChatRepository.ts
  infra/repositories/prisma/share/PrismaShareItemRepository.ts
  infra/repositories/prisma/share/PrismaShareRepository.ts
Labels: feat

#135 maplibre 타입 명시화 및 오류 해결
  app/map/components/MapView.tsx
Labels: fix

#136 나눔함 UI 수정 및 등록 시간 기준 24시간 지난건 안불러오게 하기
  app/chat/page.tsx
  app/share-box/[publicId]/page.tsx
  app/share-box/components/BottomSheet.tsx
  components/ui/drawer.tsx
  infra/repositories/prisma/share-box/PrismaShareListRepository.ts
Labels: fix, style

#140 리뷰 작성 페이지 url 수정
  app/review/[shareId]/new/components/FormRatingSelector.tsx
  app/review/[shareId]/new/hooks/useShortReviewOptions.ts
  app/review/[shareId]/new/hooks/useValidateReviewWritable.ts
  app/review/[shareId]/new/page.tsx
Labels: fix

#144 나눔 헤더에서 이미지 제대로 못불러오던 오류 수정
  app/chat/components/ChatRoom.tsx
  app/chat/components/ShareInfo.tsx
  app/chat/components/TogetherInfo.tsx
  application/usecases/chat/dto/ChatDetailDto.ts
  domain/repositories/chat/ChatMessageListRepository.ts
  infra/repositories/prisma/PrismaChatMessageListRepository.ts
Labels: fix

#147 회원가입 에러 수정
  app/auth/onboarding/components/ButtonSection.tsx
  app/auth/onboarding/page.tsx
  app/login/components/LastLoginInfo.tsx
  app/review/[shareId]/new/page.tsx
  middleware.ts
Labels: fix

#148 여러 에러 수정(채팅, 나눔함 관련)
  app/chat/components/ChatList.tsx
  app/chat/components/TogetherInfo.tsx
  infra/repositories/prisma/share-box/PrismaShareListRepository.ts
Labels: fix

#149 나눔 채팅방 목록에서 썸네일 추가
  app/chat/components/ChatList.tsx
  app/chat/components/Tab.tsx
  app/chat/page.tsx
  application/usecases/chat/dto/ChatListItemDto.ts
  infra/repositories/prisma/PrismaChatListRepository.ts
  package-lock.json
Labels: feat, fix, style

#150 삭제된 게시글 처리 및 폼 미조회 오류 수정
  app/group-buy/[groupBuyId]/edit/page.tsx
  application/usecases/group-buy/GetGroupBuyFormDetailUsecase.ts
  application/usecases/share/GetShareFormDetailUsecase.ts
  domain/repositories/group-buy/GroupBuyRepository.ts
  domain/repositories/share/ShareRepository.ts
  infra/repositories/prisma/group-buy/PrismaGroupBuyRepository.ts
  infra/repositories/prisma/share/PrismaShareRepository.ts
Labels: fix

#152 나눔함 바텀시트에 white-space 추가
  components/common/shares/Content.tsx
  manifest.json
  next-pwa.d.ts
  next.config.ts
  package-lock.json
  package.json
Labels: feat, fix, chore

#156 마이페이지 - 나누미 애니메이션 추가
  app/globals.css
  app/layout.tsx
  app/login/page.tsx
  app/users/[publicId]/edit-address/page.tsx
  app/users/[publicId]/page.tsx
  app/users/components/MyCharacter.tsx
  app/users/components/UsersNav.tsx
  app/users/components/model/Ground.tsx
  app/users/components/model/Nanumi.tsx
Labels: feat, refactor

#157 나눔 채팅방 중복참여 현상 수정
  application/usecases/join/CreateJoinUsecase.ts
  domain/repositories/share/ShareChatRepository.ts
  infra/repositories/prisma/share/PrismaShareChatRepository.ts
Labels: fix

#162 메인 페이지 활동 수치 api 연동 작업
  app/api/group-buys/count/route.ts
  app/api/shares/count/route.ts
  app/components/EndSection.tsx
  app/components/HeroSection.tsx
  app/map/components/MapView.tsx
  app/map/page.tsx
  application/usecases/group-buy/GetGroupBuyCountUsecase.ts
  application/usecases/share/GetShareCountUsecase.ts
  components/common/Footer.tsx
  domain/repositories/group-buy/GroupBuyRepository.ts
  domain/repositories/share/ShareRepository.ts
  infra/repositories/prisma/group-buy/PrismaGroupBuyRepository.ts
  infra/repositories/prisma/share/PrismaShareRepository.ts
  middleware.ts
Labels: feat, style

#163 폼 관련 에러 수정
  app/group-buy/[groupBuyId]/edit/page.tsx
  app/register/group-buy/page.tsx
  app/register/share/page.tsx
  app/review/[shareId]/new/page.tsx
  app/share/[shareId]/edit/page.tsx
  components/common/FormImageUpload.tsx
  components/common/register/FormMultiImageUpload.tsx
  infra/repositories/prisma/share/PrismaShareRepository.ts
  lib/constants.ts
Labels: fix

#165 메인페이지 section 별 간격 및 스크롤 에러 수정
  app/components/EndSection.tsx
  app/components/MapSection.tsx
  app/components/ScrollSection.tsx
  app/map/page.tsx
  components/lotties/IntroLottie.tsx
Labels: fix, style

#166 나눔 상세 페이지 접근 권한 변경 및 스크롤 관련 이슈 수정
  app/group-buy/[groupBuyId]/edit/page.tsx
  app/layout.tsx
  app/register/group-buy/page.tsx
  app/register/share/page.tsx
  app/review/[shareId]/new/page.tsx
  app/share/[shareId]/edit/page.tsx
  middleware.ts
Labels: fix

#169 fix: 삭제된 채팅방 헤더 조건 추가
  app/chat/[chatId]/shares/page.tsx
  app/chat/[chatId]/together/page.tsx
  app/chat/components/ChatHeader.tsx
  app/chat/components/ChatRoom.tsx
  app/chat/components/ShareInfo.tsx
  app/chat/components/TogetherInfo.tsx
  application/usecases/chat/dto/ChatDetailDto.ts
  domain/repositories/chat/ChatMessageListRepository.ts
  domain/repositories/chat/GroupBuyChatMessageRepository.ts
  infra/repositories/prisma/PrismaChatMessageListRepository.ts
  infra/repositories/prisma/PrismaGroupBuyChatMessageRepository.ts
Labels: fix

#173 채팅 관련 dto 수정
  app/api/chat/[chatId]/shares/confirm/route.ts
  application/usecases/chat/dto/UpdateMeetingDateDto.ts
Labels: fix

#175 각종 에러 수정 및 스타일 수정
  app/chat/components/ChatHeader.tsx
  app/chat/components/ChatList.tsx
  app/chat/components/ChatMessage.tsx
  app/chat/components/ChatMessageList.tsx
  app/chat/components/ChatRoom.tsx
  app/chat/components/ShareInfo.tsx
  app/chat/components/TogetherInfo.tsx
  app/map/components/MapList.tsx
Labels: fix, style

#178 삭제 모달 위치 이슈 수정
  components/ui/alert-dialog.tsx
Labels: fix

#184 Cluster 기한 경과 시에도 리스트에 보이는 현상
  infra/repositories/prisma/group-buy/PrismaGroupBuyRepository.ts
Labels: fix
